#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-powermanagement
Version  : 1.0.0
Release  : 10
URL      : https://github.com/lxqt/lxqt-powermanagement/releases/download/1.0.0/lxqt-powermanagement-1.0.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-powermanagement/releases/download/1.0.0/lxqt-powermanagement-1.0.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-powermanagement/releases/download/1.0.0/lxqt-powermanagement-1.0.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kidletime-dev
BuildRequires : liblxqt-dev
BuildRequires : qtbase-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : solid-dev

%description
# lxqt-powermanagement
## Overview
This repository is providing tools to monitor power management events and optionally trigger actions like e. g. shut down a system when laptop batteries are low on power.

%prep
%setup -q -n lxqt-powermanagement-1.0.0
cd %{_builddir}/lxqt-powermanagement-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636129384
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1636129384
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-powermanagement
cp %{_builddir}/lxqt-powermanagement-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-powermanagement/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
